// Code generated by mockery v2.23.2. DO NOT EDIT.

package mocks

import (
	models "timetracker/models"

	mock "github.com/stretchr/testify/mock"
)

// RepositoryI is an autogenerated mock type for the RepositoryI type
type RepositoryI struct {
	mock.Mock
}

// CreateEntryTags provides a mock function with given fields: entryID, tagList
func (_m *RepositoryI) CreateEntryTags(entryID uint64, tagList []models.Tag) error {
	ret := _m.Called(entryID, tagList)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, []models.Tag) error); ok {
		r0 = rf(entryID, tagList)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTag provides a mock function with given fields: e
func (_m *RepositoryI) CreateTag(e *models.Tag) error {
	ret := _m.Called(e)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Tag) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteEntryTags provides a mock function with given fields: entryID
func (_m *RepositoryI) DeleteEntryTags(entryID uint64) error {
	ret := _m.Called(entryID)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(entryID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTag provides a mock function with given fields: id
func (_m *RepositoryI) DeleteTag(id uint64) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetEntryTags provides a mock function with given fields: entryID
func (_m *RepositoryI) GetEntryTags(entryID uint64) ([]*models.Tag, error) {
	ret := _m.Called(entryID)

	var r0 []*models.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) ([]*models.Tag, error)); ok {
		return rf(entryID)
	}
	if rf, ok := ret.Get(0).(func(uint64) []*models.Tag); ok {
		r0 = rf(entryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(entryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTag provides a mock function with given fields: id
func (_m *RepositoryI) GetTag(id uint64) (*models.Tag, error) {
	ret := _m.Called(id)

	var r0 *models.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (*models.Tag, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint64) *models.Tag); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserTags provides a mock function with given fields: userID
func (_m *RepositoryI) GetUserTags(userID uint64) ([]*models.Tag, error) {
	ret := _m.Called(userID)

	var r0 []*models.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) ([]*models.Tag, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint64) []*models.Tag); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateEntryTags provides a mock function with given fields: entryID, tagList
func (_m *RepositoryI) UpdateEntryTags(entryID uint64, tagList []models.Tag) error {
	ret := _m.Called(entryID, tagList)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, []models.Tag) error); ok {
		r0 = rf(entryID, tagList)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTag provides a mock function with given fields: e
func (_m *RepositoryI) UpdateTag(e *models.Tag) error {
	ret := _m.Called(e)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Tag) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRepositoryI interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepositoryI creates a new instance of RepositoryI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepositoryI(t mockConstructorTestingTNewRepositoryI) *RepositoryI {
	mock := &RepositoryI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
