stages:
  - unit-test
  - integration-test

variables:
  DOCKER_IMAGE_NAME: docker-test-image

unit-test:
  stage: unit-test
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker run $DOCKER_IMAGE_NAME go test -v ./internal/...
integration-test:
  stage: integration-test
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker run $DOCKER_IMAGE_NAME go test -v ./integration_test/...
  needs:
    - job: unit-test